#!/usr/bin/env python3
#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

"""
Generates the `FHIRTypeWithExtensions` conformances for all ModelsR4 types that carry a settable `extension` property.

Since FHIRModels 0.9, `Element`, `BackboneElement`, and `DomainResource` are protocols rather than classes.
A protocol cannot be conformed to another protocol, so the conformance has to be declared for every concrete type instead.

Usage (from the package root, after `swift package resolve`):
    python3 Scripts/generate_extension_conformances.py

The ModelsR4 sources are located in the resolved FHIRModels checkout; set `FHIRMODELS_SOURCES` to override the location.
"""

import glob
import os
import re
import sys

PACKAGE_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OUTPUT_PATH = os.path.join(PACKAGE_ROOT, "Sources", "FHIRModelsExtensions", "FHIRTypeWithExtensions+Conformances.swift")
CHECKOUT_CANDIDATES = [
    os.environ.get("FHIRMODELS_SOURCES"),
    os.path.join(PACKAGE_ROOT, ".build", "checkouts", "FHIRModels", "Sources", "ModelsR4"),
    os.path.join(PACKAGE_ROOT, ".derivedData", "SourcePackages", "checkouts", "FHIRModels", "Sources", "ModelsR4"),
]

# Only the FHIR element and resource hierarchies get the conformance, mirroring the pre-0.9 conformances on `Element` and `DomainResource`.
BASE_PROTOCOLS = {"Element", "BackboneElement", "DomainResource"}
DECLARATION = re.compile(r"^public (?:struct|final class) (\w+)\s*:\s*([^{]+)\{", re.MULTILINE)
EXTENSION_PROPERTY = re.compile(r"public var `extension`: \[Extension\]\?")

HEADER = """//
// This source file is part of the Stanford Spezi open source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// This file was generated by `Scripts/generate_extension_conformances.py` from FHIRModels {version}. Do not edit it by hand.
// swiftlint:disable file_length

public import ModelsR4

"""


def find_models_r4_sources():
    for candidate in CHECKOUT_CANDIDATES:
        if candidate and os.path.isdir(candidate):
            return candidate
    sys.exit("Could not locate the FHIRModels ModelsR4 sources. Run `swift package resolve` first, or set FHIRMODELS_SOURCES.")


def resolved_fhirmodels_version():
    resolved_path = os.path.join(PACKAGE_ROOT, "Package.resolved")
    if not os.path.isfile(resolved_path):
        return "unknown"
    with open(resolved_path, encoding="utf-8") as file:
        contents = file.read()
    match = re.search(r'"identity"\s*:\s*"fhirmodels".*?"version"\s*:\s*"([^"]+)"', contents, re.DOTALL)
    return match.group(1) if match else "unknown"


def collect_types(sources_directory):
    types = set()
    for path in sorted(glob.glob(os.path.join(sources_directory, "*.swift"))):
        with open(path, encoding="utf-8") as file:
            source = file.read()
        for match in DECLARATION.finditer(source):
            base_protocols = {protocol.strip() for protocol in match.group(2).split(",")}
            if not base_protocols & BASE_PROTOCOLS:
                continue
            body_start = match.end()
            body_end = source.find("\npublic ", body_start)
            body = source[body_start:body_end if body_end > 0 else len(source)]
            if EXTENSION_PROPERTY.search(body):
                types.add(match.group(1))
    return sorted(types)


def main():
    sources_directory = find_models_r4_sources()
    types = collect_types(sources_directory)
    if not types:
        sys.exit(f"No types with an `extension` property found in {sources_directory}.")
    with open(OUTPUT_PATH, "w", encoding="utf-8") as file:
        file.write(HEADER.format(version=resolved_fhirmodels_version()))
        for type_name in types:
            file.write(f"extension ModelsR4.{type_name}: FHIRTypeWithExtensions {{}}\n")
    print(f"Wrote {len(types)} conformances to {os.path.relpath(OUTPUT_PATH, PACKAGE_ROOT)}")


if __name__ == "__main__":
    main()
